-- Texas natives, common houseplants, and garden favorites for LeafBuddy
-- Skips any plant whose name already exists in plant_species

INSERT INTO plant_species (
  id, name, scientific_name, description, care_tips,
  recommended_watering_interval_days, recommended_fertilizing_interval_days,
  light_requirement, humidity_preference, is_system, moderation_status,
  created_at, updated_at
)
SELECT
  p.id, p.name, p.scientific_name, p.description, p.care_tips,
  p.recommended_watering_interval_days, p.recommended_fertilizing_interval_days,
  p.light_requirement, p.humidity_preference, p.is_system, p.moderation_status,
  p.created_at, p.updated_at
FROM (
  SELECT UUID() AS id, 'Texas Sage' AS name, 'Leucophyllum frutescens' AS scientific_name,
    'A heat-loving native shrub with silvery foliage and purple blooms after rain. Extremely drought tolerant once established.' AS description,
    'Plant in full sun and well-draining soil. Water deeply but infrequently. Prune lightly after flowering. Thrives in Texas heat and alkaline soils.' AS care_tips,
    14 AS recommended_watering_interval_days, 60 AS recommended_fertilizing_interval_days,
    'direct' AS light_requirement, 'low' AS humidity_preference, 1 AS is_system, 'approved' AS moderation_status, NOW(3) AS created_at, NOW(3) AS updated_at
  UNION ALL SELECT UUID(), 'Esperanza', 'Tecoma stans', 'Bright yellow trumpet flowers on a tough Texas-friendly shrub. Hummingbird magnet.', 'Full sun to part shade. Water weekly when young; very drought tolerant when mature. Cut back in late winter to encourage bushy growth.', 7, 45, 'direct', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Turk''s Cap', 'Malvaviscus arboreus', 'Shade-tolerant Texas native with red twisted flowers. Great for understory and pollinators.', 'Tolerates shade to part sun. Keep soil moist during establishment. Spreads by roots; divide in fall or spring.', 5, 45, 'medium', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Texas Red Yucca', 'Hesperaloe parviflora', 'Grass-like succulent with coral flower spikes. Not a true yucca but equally tough in Texas landscapes.', 'Full sun and excellent drainage required. Water sparingly. Remove spent flower stalks. Nearly maintenance-free once established.', 14, 90, 'direct', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Prickly Pear Cactus', 'Opuntia engelmannii', 'Iconic Texas cactus with paddle pads and yellow flowers. Edible pads and fruit when prepared properly.', 'Full sun. Almost no supplemental water needed. Plant in rocky or sandy soil. Handle with thick gloves when transplanting.', 21, 120, 'direct', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Lantana', 'Lantana camara', 'Heat-tolerant flowering shrub common across Texas. Attracts butterflies all summer.', 'Full sun. Water until established, then moderate drought tolerance. Deadhead for continuous blooms.', 7, 30, 'direct', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Salvia Greggii', 'Salvia greggii', 'Autumn sage — a Texas garden staple with red, pink, or coral tubular flowers.', 'Full sun to light shade. Well-draining soil. Shear back after bloom cycles. Very drought tolerant.', 10, 45, 'direct', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Purple Coneflower', 'Echinacea purpurea', 'Hardy prairie perennial with daisy-like purple blooms. Native to much of the central US including Texas.', 'Full sun to part shade. Moderate water. Deadhead to extend flowering. Divide clumps every few years.', 7, 45, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Black-eyed Susan', 'Rudbeckia hirta', 'Cheerful yellow wildflower perennial. Self-seeds readily in Texas gardens.', 'Full sun. Tolerates heat and dry spells. Water during prolonged drought. Cut back in late fall.', 7, 60, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Crape Myrtle', 'Lagerstroemia indica', 'Summer-blooming Texas landscape favorite with long-lasting flower clusters.', 'Full sun for best blooms. Water deeply weekly in summer when young. Prune in late winter.', 7, 30, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Mexican Mint Marigold', 'Tagetes lucida', 'Anise-scented herb used as a tarragon substitute. Blooms bright yellow in fall across Texas.', 'Full sun to part shade. Regular water in summer heat. Harvest leaves before frost.', 5, 30, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Bluebonnet', 'Lupinus texensis', 'Texas state flower. Winter annual sown in fall for spectacular spring blue meadows.', 'Full sun. Sow scarified seed in October–December. Very drought tolerant. Do not overwater.', 14, 90, 'direct', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Spider Plant', 'Chlorophytum comosum', 'Classic easy houseplant with arching striped leaves and baby plantlets.', 'Bright indirect light. Water when top inch of soil dries. Propagate plantlets in water.', 7, 30, 'medium', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'ZZ Plant', 'Zamioculcas zamiifolia', 'Glossy, architectural leaves on thick stems. Tolerates low light and infrequent watering.', 'Low to bright indirect light. Let soil dry completely between waterings. Avoid overwatering.', 14, 60, 'low', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Rubber Plant', 'Ficus elastica', 'Bold indoor tree with large dark green or burgundy leaves.', 'Bright indirect light. Water when top 2 inches dry. Stable location — dislikes drafts.', 7, 30, 'bright_indirect', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Heartleaf Philodendron', 'Philodendron hederaceum', 'Trailing vine with heart-shaped leaves. One of the most forgiving houseplants.', 'Medium to bright indirect light. Water when top inch dries. Easy to propagate in water.', 7, 30, 'medium', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Chinese Evergreen', 'Aglaonema commutatum', 'Colorful patterned foliage plant that handles lower light better than most tropicals.', 'Low to medium indirect light. Keep lightly moist. Warm temperatures above 65°F.', 7, 45, 'low', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Aloe Vera', 'Aloe barbadensis', 'Succulent medicinal plant common in Texas homes and gardens.', 'Bright light indoors or full sun outdoors. Water deeply then let soil dry fully. Excellent drainage essential.', 14, 60, 'direct', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Jade Plant', 'Crassula ovata', 'Thick succulent leaves on a woody stem. Thrives on neglect.', 'Bright light. Water only when soil is completely dry. Can live decades with minimal care.', 14, 60, 'bright_indirect', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Boston Fern', 'Nephrolepis exaltata', 'Lush feathery fronds for humid spots. Classic porch and bathroom plant.', 'Bright indirect light. Keep soil consistently moist and humidity high. Mist regularly.', 3, 30, 'medium', 'high', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'African Violet', 'Saintpaulia ionantha', 'Compact flowering houseplant with velvety leaves and year-round blooms.', 'Bright indirect light. Water from bottom to avoid leaf spots. Warm stable temperatures.', 5, 30, 'medium', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Anthurium', 'Anthurium andraeanum', 'Glossy heart-shaped leaves with long-lasting waxy red or pink spathes.', 'Bright indirect light. Keep soil lightly moist. High humidity helps.', 5, 30, 'bright_indirect', 'high', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Calathea', 'Calathea ornata', 'Striking patterned foliage that moves with the day/night cycle.', 'Medium indirect light. Consistent moisture and high humidity. Use filtered water.', 5, 30, 'medium', 'high', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Ponytail Palm', 'Beaucarnea recurvata', 'Bulbous trunk with cascading grass-like leaves. Drought-tolerant and sculptural.', 'Bright light. Water sparingly — stores water in caudex. Slow grower indoors.', 14, 60, 'bright_indirect', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Cast Iron Plant', 'Aspidistra elatior', 'Nearly indestructible shade plant with dark green strappy leaves.', 'Low to medium light. Water when dry. Perfect for dim corners.', 10, 60, 'low', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Hoya', 'Hoya carnosa', 'Wax plant with thick trailing vines and fragrant star-shaped flower clusters.', 'Bright indirect light. Let soil dry between waterings. Do not cut flower spurs.', 10, 45, 'bright_indirect', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Bird of Paradise', 'Strelitzia reginae', 'Large banana-like leaves; can flower indoors with enough light.', 'Brightest indirect light available. Water when top 2 inches dry. Needs space indoors.', 7, 30, 'bright_indirect', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Dracaena Marginata', 'Dracaena marginata', 'Spiky red-edged leaves on thin woody canes. Modern and low-maintenance.', 'Medium to bright indirect light. Water when top half of soil dries.', 10, 45, 'medium', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Tomato', 'Solanum lycopersicum', 'The quintessential summer garden crop. Choose heat-set types for Texas.', 'Full sun, 6+ hours. Deep consistent watering. Mulch to retain moisture. Plant after last frost.', 3, 14, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Bell Pepper', 'Capsicum annuum', 'Sweet peppers in red, yellow, orange, or green. Great in raised beds.', 'Full sun. Even moisture. Stake or cage plants. Harvest regularly.', 3, 14, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Jalapeno Pepper', 'Capsicum annuum', 'Texas kitchen staple. Prolific hot pepper that loves long warm seasons.', 'Full sun and warm soil. Water deeply 2–3 times per week in summer. Very productive in Texas.', 3, 14, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Okra', 'Abelmoschus esculentus', 'Southern and Texas garden classic. Thrives in heat when other crops struggle.', 'Full sun. Heat-loving. Regular harvest keeps plants producing. Drought tolerant once established.', 4, 21, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Basil', 'Ocimum basilicum', 'Essential kitchen herb for pesto and summer cooking. Loves Texas warmth.', 'Full sun to part shade. Keep soil moist. Pinch flower buds to extend leaf harvest.', 3, 21, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Cilantro', 'Coriandrum sativum', 'Cool-season herb for salsa and tacos. Bolts quickly in Texas heat — succession plant.', 'Morning sun, afternoon shade in summer. Sow every few weeks in spring and fall.', 3, 21, 'medium', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Chives', 'Allium schoenoprasum', 'Mild onion-flavored herb with edible purple flowers. Perennial in Texas gardens.', 'Full sun to part shade. Cut leaves regularly. Divide clumps every 2–3 years.', 5, 30, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Dill', 'Anethum graveolens', 'Feathery herb for pickles, fish, and salads. Fast-growing annual.', 'Full sun. Keep soil evenly moist. Succession sow every 2 weeks. Attracts swallowtail butterflies.', 3, 21, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Oregano', 'Origanum vulgare', 'Mediterranean herb that handles Texas heat. Essential for pizza and Mexican dishes.', 'Full sun. Let soil dry between waterings. Harvest before flowering for strongest flavor.', 7, 30, 'direct', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Thyme', 'Thymus vulgaris', 'Low woody herb with tiny aromatic leaves. Excellent edging plant.', 'Full sun and sharp drainage. Very drought tolerant. Trim after flowering.', 10, 45, 'direct', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Rosemary', 'Salvia rosmarinus', 'Woody evergreen herb that thrives in Texas heat. Ubiquitous in Hill Country gardens.', 'Full sun. Excellent drainage. Minimal watering once established.', 10, 45, 'direct', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Mint', 'Mentha spicata', 'Aggressive spreading herb for tea and mojitos. Best contained in pots.', 'Partial sun to shade. Keep moist. Grow in containers to prevent garden takeover.', 3, 21, 'medium', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Parsley', 'Petroselinum crispum', 'Biennial herb for garnishes and cooking. Does well in Texas spring and fall.', 'Full sun to part shade. Consistent moisture. Provide shade in peak summer heat.', 4, 21, 'medium', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Lavender', 'Lavandula angustifolia', 'Fragrant purple spikes beloved in Texas gardens. Needs drainage and air circulation.', 'Full sun. Sandy soil. Water sparingly — root rot is the main killer.', 10, 45, 'direct', 'low', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Green Beans', 'Phaseolus vulgaris', 'Fast-producing bush or pole beans. Great kid-friendly Texas garden crop.', 'Full sun. Regular water during flowering. Pick daily for continuous harvest.', 3, 14, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Cucumber', 'Cucumis sativus', 'Crisp summer vines for salads and pickles. Trellis vertically to save space.', 'Full sun. Consistent moisture critical. Harvest young for best texture.', 3, 14, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Zucchini', 'Cucurbita pepo', 'Prolific summer squash. One plant can feed a neighborhood in Texas.', 'Full sun. Heavy feeder and drinker. Harvest at 6–8 inches for best flavor.', 3, 14, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Lettuce', 'Lactuca sativa', 'Cool-season salad green. Grow in Texas fall, winter, and early spring.', 'Part sun in spring. Shallow frequent watering. Bolt-resistant varieties for Texas.', 3, 14, 'medium', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Kale', 'Brassica oleracea', 'Nutrient-dense leafy green that sweetens after light frost. Texas fall/winter crop.', 'Full sun to part shade. Harvest lower leaves first. Tolerates light freezes.', 4, 21, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Strawberry', 'Fragaria × ananassa', 'Sweet perennial fruit for containers and raised beds.', 'Full sun. Consistent moisture during fruiting. Mulch to keep fruit clean.', 3, 21, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Sunflower', 'Helianthus annuus', 'Cheerful towering annual. Great for kids and pollinators.', 'Full sun. Moderate water. Stake tall varieties. Birds love the seeds.', 5, 30, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Marigold', 'Tagetes erecta', 'Bright annual flower that repels some garden pests. Workhorse of Texas flower beds.', 'Full sun. Tolerates heat and poor soil. Deadhead for more blooms.', 5, 30, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
  UNION ALL SELECT UUID(), 'Zinnia', 'Zinnia elegans', 'Heat-loving cut flower that blooms all summer in Texas.', 'Full sun. Water at soil level. Deadhead spent blooms. Excellent cut flowers.', 5, 21, 'direct', 'moderate', 1, 'approved', NOW(3), NOW(3)
) AS p
WHERE NOT EXISTS (SELECT 1 FROM plant_species ps WHERE ps.name = p.name);

SELECT COUNT(*) AS total_species FROM plant_species;